#pragma once

#define XPLOAD_VERSION_STRING 
#define XPLOAD_VERSION_MAJOR 
#define XPLOAD_VERSION_MINOR 
#define XPLOAD_VERSION_PATCH 
#define XPLOAD_VERSION_HEXA ((XPLOAD_VERSION_MAJOR << 24) | (XPLOAD_VERSION_MINOR << 16) | (XPLOAD_VERSION_PATCH << 8))
