on: [push]
jobs:
    Backend-Client-Functional-Tests-CI:
        runs-on: ubuntu-20.04
        steps:
            - name: Setup SSH Keys and known_hosts
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

            - name: Check out the commit that triggered this job
              uses: actions/checkout@v3
              with:
                path: ${{ github.event.repository.name }}

            - name: Check out nopayloaddb
              env:
                  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  git clone git@github.com:BNLNPPS/nopayloaddb.git
                  cd nopayloaddb && git pull origin master

            - name: gypsy trick - replace one line of code in dockerfile
              run: sed -i 's/FROM python:3/FROM python:3.7.5/g' nopayloaddb/Dockerfile

            - name: Build & launch npdb container
              run: |
                  cd nopayloaddb && docker-compose up --build -d
                  sleep 30

            - name: test curl
              run: curl http://localhost:8000/api/cdb_rest/gt

            - name: run nopayloadclient tests
              run: |
                  pwd
                  ls
                  cd nopayloadclient
                  pwd
                  ls
                  cmake -S . -B build && cmake --build build/ && cd build/ && ctest --verbose
