on: [push]
jobs:
    Backend-Client-Functional-Tests-CI:
        runs-on: ubuntu-20.04
        steps:
            - name: Deploy Stage
              uses: actions/github-script@v6
              id: my-script
              with:
                script: |
                  github.rest.actions.createWorkflowDispatch({
                    'ligerlac',
                    'sphenixnpc',
                    'workflows/backend-client-functional-tests.yaml',
                    'main',
                  })